const nodes = [
  {
    id: "000001",
    selectedProject: "Project A",
    selectedSeverity: "Minor",
    selectedPriority: "Low",
    selectedAssignee: "Unassigned",
    summaryText: "Login Page Styling",
    descriptionText: "Styling issue with the login page. Need to fix the alignment.",
    status: "New",
  },
  {
    id: "000002",
    selectedProject: "Project B",
    selectedSeverity: "Major",
    selectedPriority: "Medium",
    selectedAssignee: "User 1",
    summaryText: "Bug in Dashboard",
    descriptionText: "There is a bug in the dashboard that causes data inconsistency. Need to investigate and fix.",
    status: "Work in Progress",
  },
  {
    id: "000003",
    selectedProject: "Project C",
    selectedSeverity: "Feature",
    selectedPriority: "High",
    selectedAssignee: "User 2",
    summaryText: "Add Dark Mode Feature",
    descriptionText: "Implement dark mode feature for the application as requested by users.",
    status: "Resolved",
  },
  {
    id: "000004",
    selectedProject: "Project A",
    selectedSeverity: "Crash",
    selectedPriority: "High",
    selectedAssignee: "User 3",
    summaryText: "Application Crashes on Startup",
    descriptionText: "Users report that the application crashes upon startup. Urgent fix needed.",
    status: "New",
  },
  {
    id: "000005",
    selectedProject: "Project B",
    selectedSeverity: "Styling",
    selectedPriority: "Medium",
    selectedAssignee: "Unassigned",
    summaryText: "Footer Alignment Issue",
    descriptionText: "The footer is not aligning properly. Need to adjust the styling for better alignment.",
    status: "Work in Progress",
  },
  {
    id: "000006",
    selectedProject: "Project C",
    selectedSeverity: "Feature",
    selectedPriority: "Low",
    selectedAssignee: "User 1",
    summaryText: "Implement User Profile",
    descriptionText: "Create a user profile page with customizable settings and preferences.",
    status: "Resolved",
  },
  {
    id: "000007",
    selectedProject: "Project A",
    selectedSeverity: "Major",
    selectedPriority: "High",
    selectedAssignee: "User 2",
    summaryText: "Database Connection Issue",
    descriptionText:
      "Users report intermittent issues connecting to the database. Investigate and resolve the problem.",
    status: "New",
  },
  {
    id: "000008",
    selectedProject: "Project B",
    selectedSeverity: "Styling",
    selectedPriority: "Medium",
    selectedAssignee: "User 3",
    summaryText: "Improve Landing Page Layout",
    descriptionText: "Enhance the layout and design of the landing page to improve user experience.",
    status: "Work in Progress",
  },
  {
    id: "000009",
    selectedProject: "Project C",
    selectedSeverity: "Minor",
    selectedPriority: "Low",
    selectedAssignee: "Unassigned",
    summaryText: "Update Contact Form Validation",
    descriptionText: "Update and validate the contact form to ensure accurate data submission.",
    status: "Resolved",
  },
  {
    id: "000010",
    selectedProject: "Project A",
    selectedSeverity: "Crash",
    selectedPriority: "High",
    selectedAssignee: "User 1",
    summaryText: "Application Freezing on Mobile",
    descriptionText: "Users experience freezing issues on the mobile version of the application. Urgent fix required.",
    status: "New",
  },
];
